### ISSUE TITLE
Simplify engine `Store` contract to CRUD, push more logic into upper layer

### ISSUE THREAD

**Issue by ghost** [battlesnakeio/roadmap#101]
I'd like to push for the architectural idea of simplifying the store operations more along the lines of basic CRUD and then pushing any complicated coordination stuff into a higher level like the controller layer. This would make it a lot easier to write new `Store` implementations and it would allow us to modify the behavior faster across all store implementations.

A big benefit of simplifying storage requirements is we are less likely to run into implementation differences. This should help reduce the number of bugs we will get related to differences in the underlying storage layer.

The following is the Slack conversation that lead to this issue:

> Torben [10:32 AM]
Also, I'm really asking myself why the heck I don't just implement a mongo store
Way harder to do this kinda thing on Redis than in Mongo or Postgres even
>
> daniel [10:32 AM]
Mongo is fine with me too
>
> Torben [10:32 AM]
A few things need scripting and stuff because they require conditional data updates that are atomic
So that ends up needing transactional pipelines and scripting to accomplish in redis
That's kinda why I'm noticing all these areas where the operations are "complex"
It makes it burdensome to implement stores, especially on simpler storage backends
If we could simplify that contract, then these stores would be easier to write
Make sense?
So like imagine if we used a locking mechanism in the controller to make these operations complex but not get in a weird state (edited)
We could write that atomic logic once in one place (edited)
Then all the stores don't have to care anymore, they would have simpler operations
That would get wrapped in the controller's lock
>
> daniel [10:35 AM]
Do a pr that proposes the interface changes

**Comment by torbensky** [comment]
I think probably the interface would stay largely as it already is, but some of the documented and undocumented requirements for it would be changed. For example, not requiring the running status to be checked by the storage layer, instead pushing that into the controller layer.

**Comment by torbensky** [comment]
I think there are clear benefits. There is 1 controller, 3 storage implementations (for now). Putting coordination logic in the controller means it's in one place. If we put it in Store, it means every additional thing we push into the storage layer's responsibility gets duplicated 3 times. This will lead to more bugs due to store layer implementation differences that the controller will need to rely on.

**Comment by ColDog** [comment]
@torbensky I'm lacking a little insight into how this will specifically change the architecture so can't really visualize how this will help / not help things.

**Comment by dlsteuer** [comment]
I'm happy with the current store interface.
