### ISSUE TITLE
Store.Lock should accept a time.Duration value for lock expiration

### ISSUE THREAD

**Issue by torbensky** [battlesnakeio/roadmap#103]
I don't think we should leave this up to the storage layer. It would be better if the controller was able to know how long the locks should be good for so that it could use the locks for distributed coordination more reliably.

https://github.com/battlesnakeio/engine/blob/master/controller/store.go#L35

Suggestion:
// exp is the amount of time before the lock expires. 0 means no expiry.
`Lock(ctx context.Context, key, token string, exp time.Duration) (string, error)`

**Comment by ColDog** [comment]
How could the controller use this for more reliable distributed coordination? I can't think of any use cases but seems like a small change. Just curious, maybe throw out a use case?

**Comment by torbensky** [comment]
Classic example is the try lock, wait, try again. Usually you want to wait before retrying and that wait is based somewhat off the lock expiration times. If we leave the expiration up to each persistence layer then we have trouble waiting an appropriate amount of time. Especially if the wait times are different in each persistence implementation. Not only that, what if we want to change lock expiration time? Right now, we'd have to change that in each persistence implementation every time we want to do that. This is a lot more surface area. I think logically a decision like how long locks should be kept is something that should be done by the controller.
