### ISSUE TITLE
Remove `PopGameID`, instead, list games with filters

### ISSUE THREAD

**Issue by torbensky** [battlesnakeio/roadmap#104]
https://github.com/battlesnakeio/engine/blob/master/controller/store.go#L41

Instead of this operation, make a more general operation that will list games (filterable by status). The controller could use its own locking if it wants to avoid race conditions for picking an unlocked, running game or it could just try and retry allowing the first to lock a game to win. 

Speaking from my experience implementing this method on Redis, it is not easy to do, but a list method would be.

Suggestion:
```
ListGames(context.Context, status string, limit int, offset int) ([]*pb.Game, error)
```

**Comment by dlsteuer** [comment]
I'm against this, similar to the other ticket about CRUD only, I don't think Stores are CRUD only, they also have to manage the concept for a lock around a game. ListGames is not sufficient to find a game that is unlocked and ready to be worked on.

**Comment by torbensky** [comment]
I don't feel as strongly about this as I do about the CRUD stuff but I also think this isn't tied to that. I believe a list method would be better because it leaves more flexibility for future needs (can retrieve other types of games) while also solving the problem we have right now (retrieving only 1 type of game). Seems win-win to me so I'm not sure what the objection is about?

**Comment by ColDog** [comment]
This would push game selection algorithm to the worker instead of the controller. What is the advantage of pushing it to the worker? To me, it seems that keeping the game selection algorithm in the controller is more valuable.
