### ISSUE TITLE
Add Store.Close` method

### ISSUE THREAD

**Issue by torbensky** [battlesnakeio/roadmap#105]
It's possible that a lot of stores will need to cleanup some things. We should probably add a `Close` method to the `Store` interface. Implementations that don't require cleanup can just do a no-op.

Suggestion:
`Close() error`

**Comment by dlsteuer** [comment]
I would suggest making this a separate interface something like StoreCloser with a close method. This would be more idiomatic go imo

**Comment by ColDog** [comment]
+1 @dlsteuer ya or use `io.Closer`

**Comment by dlsteuer** [comment]
Yup this is done in battlesnakeio/engine#42
