### ISSUE TITLE
Snake doesn't die when it crashes into itself

### ISSUE THREAD

**Issue by graeme-hill** [battlesnakeio/roadmap#110]
I ran a game and one of the snakes did a U-turn, drove through itself, and did not die. This is just a guess but the bug may be that the server doesn't detect that you should die if you do a U-turn?

It would be a good idea to try to reproduce this with a test and then make the test pass.

**Comment by graeme-hill** [comment]
Here are all the frames from the game

[frames.txt](https://github.com/battlesnakeio/roadmap/files/2117325/frames.txt)

**Comment by nbw** [comment]
I'd like to take this one if I have some time over the next week or so.

**Comment by dlsteuer** [comment]
just realized the problem is completely because of this if statement https://github.com/battlesnakeio/engine/blob/master/rules/death.go#L42 so should be pretty easy to fix.

**Comment by nbw** [comment]
PR [here](https://github.com/battlesnakeio/engine/pull/43)

**Comment by dlsteuer** [comment]
PR merged
