### ISSUE TITLE
Keep snakes alive once they're added to a tournament bracket - django command

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#111]
It sucks when you spend all day writing a snake and then it dies due to heroku shutdown 

 Acceptance
- ping for aliveness every 30 seconds.
- display somehow in the tournament dashboard that a snake is non-responsive
- display snake status in the play interface 

Implementation idea
- background job to ping snakes.

**Comment by brandonb927** [comment]
We now have the ping endpoint in all snakes and implemented functionality in the engine, correct?

**Comment by dlsteuer** [comment]
what do you mean by in the engine? The engine only validates the ping endpoint but doesn't call it ever.

**Comment by brandonb927** [comment]
Gotcha, that's the part I wasn't sure on. So, ideally Play handles this I think?

**Comment by aforsilly** [comment]
@codeallthethingz can you clarify what info needs to be passed on? Should this be included in the welcome @brandonb927?

**Comment by brandonb927** [comment]
I think the main point we wanted was to ensure that day-of, during registration, the attendees are informed that we may disqualify a teams snake if it does not respond correctly and in the appropriate time window during the tournament, and that extra care should be taken before the tournament to ensure this happens by team members. Something like that

**Comment by codeallthethingz** [comment]
Daniel: write a django job, can add to the existing or write a new cron schedule.

**Comment by joram** [comment]
https://github.com/joram/play/tree/keepalive-snakes-in-active-tournaments

**Comment by codeallthethingz** [comment]
Moved to play repo
