### ISSUE TITLE
Bad Request (400) when starting play

### ISSUE THREAD

**Issue by matthieudolci** [battlesnakeio/roadmap#114]
When trying to deploy Play on our production environment, we keep getting a `Bad Request (400)` error page [https://play.battlesnake.io](https://play.battlesnake.io)

The database has been setup with: `django-admin migrate`

There is also a weird behavior where we will get a 400 when debug is off, but if debug is turn on the login page will load.

The same error can be reproduce locally.

**Comment by codeallthethingz** [comment]
@matthieudolci what do the logs say?

**Comment by matthieudolci** [comment]
The logs are empty

**Comment by brandonb927** [comment]
I got a 400 when running this locally when I didn't have the Postgres stuff setup correctly.

**Comment by brandonb927** [comment]
@matthieudolci are you making sure you define the `ENV=production` flag when running? Also I think you should run the migrations with `./manage.py` instead of directly with `django-admin`?

**Comment by brandonb927** [comment]
Looks like @matthieudolci and I solved it with https://github.com/battlesnakeio/play/commit/920fa3118056afa9200a2f9277e7961f724c728c and https://github.com/battlesnakeio/play/pull/23, we can close this now!
