### ISSUE TITLE
Board doesn't resize when bigger than 20x20

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#119]
Steps to reproduce

- create a board 30x30

Expected

Screen fits in display

Actual

Truncated board.

**Comment by brandonb927** [comment]
@graeme-hill you mentioned you had some work on this front to improve resizability of the board in SVG?

**Comment by brandonb927** [comment]
This should be solved with https://github.com/battlesnakeio/board/pull/9

**Comment by brandonb927** [comment]
Closed with https://github.com/battlesnakeio/board/pull/9
