### ISSUE TITLE
Process for bounty snake ideas

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#121]
AC
- Documentation that
  - Bounty snake ideas need to modify the engine and run locally.
  - If you want the idea to be merged into the main engine with a configuration to turn it on chat with the engine maintainer / game master in the battlesnake slack channel to talk about the architectural approach and whether this is likely to make it into mainline.

Original ticket
-----
People want to add custom functionality to the engine.  
Examples include 
- Tron mode
- Infinite life
- Starting snake size
- Adding obstacles into the board.

Currently we have no facility to collect this information or to allow it to happen.

Implementation ideas
1. Use engine to proxy to another engine.  That way we can still keep game state and track wins and losses.
1. Allow some kind of plugin module to the existing engine.
1. Allow bypass of the engine on board.
1. Take ideas and manually build them in to the engine and allow an advanced configuration section to start games with these things turned on and configured.

**Comment by codeallthethingz** [comment]
@dlsteuer I like 1 or 4 the best.  What do you think?

**Comment by dlsteuer** [comment]
I like either #2 or #4 the best
