### ISSUE TITLE
Bad snakes

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#122]
As a game player
I can expect that the engine will continue to function even when given really bad snakes
such that I can iterate on my snakes without fear of breaking things
that I can know that my mistakes won't affect other snake builders
That the tournament cannot be brought to it's knees maliciously or by mistake

AC
- Engine gracefully handles crazy snake URLs and continues to function normally while giving game feedback about why the snakes are not doing much on the board.

Implementation Idea
- A set of engine integration tests that throw bad snake URLs at the engine and one good snake and the game proceeds as fast as possible.
- Youtube URL
- Snake that returns infinite response
- Snake that  responds and then times out before sending all data.
- Snake that sends binary data
- Snake that sends explosive json?
- Snake that sends really large values in valid json.  Huge snake name.  Crazy sized movement "uuuuuuuuuuuuuuuuuuuuuuup*10000000"
- Snake that sends incredibly nested json.

**Comment by dlsteuer** [comment]
I think the engine will handle all of this gracefully
