### ISSUE TITLE
Verify the battlesnakeio org on GitHub

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#123]
We should [verify this org](https://help.github.com/articles/verifying-your-organization-s-domain/) as an extra level of ownership over Battlesnake IP and the battlensnake.io domain.

**Comment by codeallthethingz** [comment]
Doh!  Realized that I created a txt record on dnssimple, but our hosting is on GCP.  Updated there and waiting for the propagation again.

**Comment by codeallthethingz** [comment]
Verified!
