### ISSUE TITLE
API to validate snake

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#125]
As a snake developer
I can test my snake and get feedback about how it is configured
Such that I can quickly see how the snake responds to different engine calls

Acceptance
- Gives a score out of 100.  100 being responds correctly to all API calls under the time limit.
- Gives helpful error messages when the response schema is wrong or the snake errors out or it times out.
- returns timing information for API responses.

Implementation notes
An API in engine call `/validateMySnake` that you send in your snake url to and get back some json describing how your snake responded to  the api calls.

```bash
> curl "engine.battlesnake.io/validateMySnake?url=dsnek.heroku.com" 
```

```json
{ 
  "score": 97,
  "start": { 
    "message": "all good",
    "responseTime": 296,
  },
  "move": {
    "message": "bad schema - responses too large, have a look at the schema docs here: <link>",
    "errors": [ "text to go in a PRE block", "more text in a pre block" ],
    "responseTime": 112,
  },
  "end": "..."
}
```

**Comment by brandonb927** [comment]
@codeallthethingz can this be closed now?

**Comment by codeallthethingz** [comment]
yes
