### ISSUE TITLE
Visualization of validate snake API

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#126]
Depends on: https://github.com/battlesnakeio/roadmap/issues/125

As a tournament goer 
I have a way to visually tell if my snake is working yet
such that I can get a fun feeling about my snake status
such that teams will be confident that their snake will at least compete in a heat

AC
- hidden behind some kinda flydown in the snakes page
- set of information displayed that gets returned from the engine by this ticket: https://github.com/battlesnakeio/roadmap/issues/125

**Comment by brandonb927** [comment]
Work for this is over at https://github.com/battlesnakeio/play/pull/52

**Comment by brandonb927** [comment]
Work on this was completed!
