### ISSUE TITLE
Play/pause/step forward/backward functionality

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#127]
As a user, I want to be able to play, pause, and step forward/backwards while re-watching a game.

This would only be applicable to a game that has been played out by the engine.

Acceptance:
- can play a game from the beginning or current frame position
- can pause a running game on the current frame
	- can step forward or backward a frame at a time while paused
- can restart the game from the first frame
- keyboard shortcuts

**Comment by brandonb927** [comment]
@graeme-hill I think @dlsteuer said engine will have to support this, so so pre-req work in engine is required for board to function here.

**Comment by dlsteuer** [comment]
Only if/when we support real time games. For now this is just game play back

**Comment by brandonb927** [comment]
This was worked on in https://github.com/battlesnakeio/board/pull/11 and this issue can now be closed! 🎉
