### ISSUE TITLE
Alive/Dead Status is not sent out to players

### ISSUE THREAD

**Issue by MarkZsombor** [battlesnakeio/roadmap#132]
In the current spec/engine unless a snake has died from hunger (health == 0) there is no way for other players to know if the other snakes in the game are alive or dead.

Schrodinger's snakes if you would.

**Comment by MarkZsombor** [comment]
This is written to spec, so the spec will need to be updated. 

Last year dead snakes were moved from the snakes object and found in their own dead_snakes object, though other solutions could be adding a flag of some sort onto the snakes (isLiving?) or changing a dead snakes health to zero.

**Comment by codeallthethingz** [comment]
This is actually a duplicate of a bug that we shouldn't send dead snakes at all.
