### ISSUE TITLE
Change in order for when death is assessed from last year.

### ISSUE THREAD

**Issue by MarkZsombor** [battlesnakeio/roadmap#134]
Last year once all the snake moves were taken in by the engine it would perform the following steps:

1. Move Head
2. Determine if Snake has eaten food
3. Remove tip of tail if no food eaten
4. Assess snakes for death conditions (such as collisions)

In this year's docs the order is as follows: 

1. Move Head
2. Assess snakes for death conditions (such as collisions)
3. Determine if Snake has eaten food
4. Remove tip of tail if no food eaten

The effect of this change is that a snake cannot move its head into a square that is currently occupied by the tip of any snake's tail without dying, as technically the tail wouldn't have been moved out of the that square before the engine checks for collisions.

The major change of this is it makes Chicken Snakes (snakes that chase their own tails) significantly harder to code, and a minor change is the board is just more cluttered (as there are effectively less free spaces on the board).

**Comment by codeallthethingz** [comment]
@MarkZsombor Discussed with @bvanvugt and we're all on the same page so we're going to revert to the same strategy as last year.

**Comment by dlsteuer** [comment]
resolved in https://github.com/battlesnakeio/engine/pull/53

**Comment by dlsteuer** [comment]
pr merged and deployed
