### ISSUE TITLE
Dead snakes in list of snakes

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#135]
We ran an internal battlesnake tournament at Sendwithus, and a couple teams discovered that dead snakes are possibly still being returned in the list of snakes that is sent to the move endpoint.

**Comment by mnursey** [comment]
I can also confirm this is an issue. It says [here](https://github.com/battlesnakeio/docs/blob/master/docs/convert-2018-to-2019.md) 

> The dead snakes are no longer removed from the snakes. If you wish to use logic based on other (living) snakes you must first determine the snakes status by looking its health in the snakes object.

Unfortunately this is not happening.

**Comment by brandonb927** [comment]
@mnursey Can you confirm this issue has been addressed for you?
