### ISSUE TITLE
Watch command for local snake development 

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#136]
A way for the engine to watch a local directory structure and if there are changes assume the snake has changed and run a new game in the cli

AC 
- engine --watch ./someDirectory

**Comment by dlsteuer** [comment]
The engine has no idea who to run a snake server in the given directory, because it may be any number of languages with any number of start up scripts. I move to close this issue as I don't think it's something the engine should be worrying about.
