### ISSUE TITLE
Lambda snake

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#143]
Take a snake and get it running in AWS Lambda or Google Functions.
Write a readme and add a PR for the snake you made serverless.

**Comment by nbw** [comment]
Node one: https://github.com/battlesnakeio/starter-snake-node/pull/16

Golang one is on the way.

**Comment by nbw** [comment]
I forgot to repost here, but https://github.com/nbw/starter-snake-go-serverless

**Comment by dlsteuer** [comment]
Thanks @nbw
