### ISSUE TITLE
Build Tournament UI

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#150]
A UI for managing a tournament for admins only.

AC:
- functionality restricted to an admin list
- can run a tournament from a list of snakes
- restricted from starting `round X` when `round X-1` has not run all games

**Comment by joram** [comment]
models done. UI remains

**Comment by codeallthethingz** [comment]
@joram  / @tristan-swu

**Comment by joram** [comment]
this ac is all in there.
