### ISSUE TITLE
Move sqlproxy out of side car

### ISSUE THREAD

**Issue by matthieudolci** [battlesnakeio/roadmap#151]
Instead of using sqlproxy side car containers to connect to postgreSQL we should implement this https://github.com/helm/charts/tree/master/stable/gcloud-sqlproxy to allow multiple applications to connect to the db from one point.

**Comment by brandonb927** [comment]
@matthieudolci has this been done?

**Comment by matthieudolci** [comment]
@brandonb927 yes all done :-)
