### ISSUE TITLE
Food spawn with delay

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#152]
As an battlesnake contestant
I am challenged by a game mechanic that requires game state to be maintained.
As a beginner programmer I can ignore this completely and just go for any food when I need it.

Instead of instantly respawning food have a predetermined length of time that the food does not respawn.

AC
- TBD

**Comment by codeallthethingz** [comment]
What if there is 1 picee of food, and thus several turns where there is no food and therefore the spawn point for the food becomes problematic.

**Comment by codeallthethingz** [comment]
Moving to icebox for 2020 event.

**Comment by dlsteuer** [comment]
We made food spawn changes for the 2019 tournament
