### ISSUE TITLE
Getting started from zero to engine running with snake steps windows

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#155]
As a snake developer I can follow a set of easy to follow steps to go from a computer with nothing on it to a working snake and engine dev mode browser working locally.

AC
- Programming environment is NodeJs
- Uses the engine dev mode facilities.
- supports windows 
- is tested on a new programmer to see where the stumbling blocks are.

**Comment by codeallthethingz** [comment]
Not closing this as we still need to do basic windows install

**Comment by brandonb927** [comment]
I added a basic Windows tutorial here <https://github.com/battlesnakeio/docs/pull/12>

**Comment by brandonb927** [comment]
Closed in https://github.com/battlesnakeio/docs/pull/12
