### ISSUE TITLE
Show the last N games on the leaderboard so they can be viewed.

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#157]

**Comment by dlsteuer** [comment]
battlesnakeio/play#56 fixes this.

**Comment by codeallthethingz** [comment]
@dlsteuer I don't think this has been deployed yet?

**Comment by dlsteuer** [comment]
No not deployed yet, but in master, so will go out with next deploy

**Comment by dlsteuer** [comment]
Now deployed
