### ISSUE TITLE
Make the timeout configurable

### ISSUE THREAD

**Issue by nbw** [battlesnakeio/roadmap#163]
The timeouts should be configurable ideally, for testing but also for the event. 

Already a comment in the code:
https://github.com/battlesnakeio/engine/blob/462797dae800bea3a18e5e61ab18e0216e2ffef0/rules/create.go#L39

> the turn timeout on the next line is not used in the engine anymore
-Daniel

**Comment by brandonb927** [comment]
@dlsteuer this is the timeout you've tried to modify in the last few PRs, correct?

**Comment by dlsteuer** [comment]
This is done.
