### ISSUE TITLE
Tournament replay-ability

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#166]
When the final work for Tournaments is done, it should include the ability to deterministically replay heats and games.

credit to @stozula

**Comment by codeallthethingz** [comment]
@brandonb927 what is deterministically in this context?

**Comment by brandonb927** [comment]
I would define it as "replays the game exactly how it played out the first time"

**Comment by brandonb927** [comment]
I think this is now covered by the Tournament UI being added by @joram and the new step fwd/back buttons, I will confirm.

**Comment by codeallthethingz** [comment]
@brandonb927 @joram is this confirmed?

**Comment by brandonb927** [comment]
I think so with the current Tournament UI and linking to games that've been played from rounds.
