### ISSUE TITLE
opt-in ability to each tournament

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#167]
As someone who attends the event, I would like to see a drop down of active tournaments, and add one of my snakes to one of the categories (I.e. 2019-junior, 2019-intermediate, or 2019-advanced)

**Comment by codeallthethingz** [comment]
This is great.

I think it should just be a drop down of `junior` `intermediate` `advanced`  as we can have a hidden element for the tournament.  

Eventually we can expose that as we figure out how other people create tournaments.  
The one we host in Victoria should be "World Finals 2019"

**Comment by codeallthethingz** [comment]
@joram / @tristan-swu

**Comment by codeallthethingz** [comment]
Completed.
