### ISSUE TITLE
ability to tweak number of initial heats on a tournament

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#168]
Previously we have had tournaments which, by default would end with 4 snakes in the final game.
Human eyes should always make the final decision of how many initial heats there are, so we can avoid a game turning in to "who of these 4 is not going to be in the top 3".

This would need to be done once all the snakes in the tournament have opted in, so you know the final count.

**Comment by codeallthethingz** [comment]
@joram / @tristan-swu

**Comment by joram** [comment]
closing because duplicate
