### ISSUE TITLE
Validate snake functionality giving false positives

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#171]
It appears that if you have a trailing slash in your snake URL (as one would have when copying from a browser, `https://example.com/`) and pasting it into the URL field in Play, the validateSnake functionality will provide a false positive warning you that there are issues with your snake on multiple endpoints. This seems to be with how the validateSnake endpoint is handling URLs here (https://github.com/battlesnakeio/engine/blob/master/rules/validate.go#L20-L42).

@dlsteuer [mentioned in Slack](https://battlesnake.slack.com/archives/C481H117Z/p1543514162081500) that there is a [URL handler function](https://github.com/battlesnakeio/engine/blob/master/rules/http.go#L70) that the rest of Engine uses, and that this functionality should also utilize it.

![kapture 2018-11-29 at 9 40 53](https://user-images.githubusercontent.com/1509352/49241682-6abdeb00-f3bd-11e8-8e67-a7d8758817db.gif)

**Comment by codeallthethingz** [comment]
From daniels comments:

there is code to deal with it

https://github.com/battlesnakeio/engine/blob/master/rules/http.go#L70
rules/http.go:70
func getURL(url, path string) string {
battlesnakeio/engineAdded by GitHub

**Comment by brandonb927** [comment]
This was fixed and can now be closed
