### ISSUE TITLE
Sanitize URLs in ValidateSnake

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#172]
From slack: 

there is code to deal with it

https://github.com/battlesnakeio/engine/blob/master/rules/http.go#L70
rules/http.go:70
```func getURL(url, path string) string {```
battlesnakeio/engineAdded by GitHub

if you call that with the url and the path you want it makes sure you are fine regardless of trailing slash

**Comment by dlsteuer** [comment]
This is a dup of #171
