### ISSUE TITLE
Initial starting heads on board are all black

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#177]
Repro
1. Start a new game
2. Don't press play yet

Expected
Snake heads are the correct colour

Actual
Snake heads are all black

**Comment by brandonb927** [comment]
I think this is actually an Engine issue... turn 0 (the frame displayed initially) there are no snake colours yet determined and it isn't until frame 1 that we receive them from the snakes?

**Comment by brandonb927** [comment]
This was fixed in https://github.com/battlesnakeio/board/pull/12
