### ISSUE TITLE
Snake highlighting for commentators

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#178]
As a commentator
I can highlight a snake(s) 
Such that I can visually talk about a highlighted snake as the game runs.
Snakes that are similar colours can be disambiguated during the game

Implementation idea
In board be able to click on a snake and have that snake be highlighted with a unique high contrast colour that is also reflected on the moving snake.
Clicking the snake a second time deselects the snake

![image](https://user-images.githubusercontent.com/1261268/49832934-ee2bf480-fd4c-11e8-9a9f-ccabc4c3e944.png)

**Comment by codeallthethingz** [comment]
@stozula what do you think?

**Comment by codeallthethingz** [comment]
Graeme some kinda identifier could be used.

**Comment by brandonb927** [comment]
This should satisfy the AC here https://github.com/battlesnakeio/board/pull/14

**Comment by codeallthethingz** [comment]
> <@U9VRK01FA> <https://user-images.githubusercontent.com/1509352/50253224-5b1f3a00-039e-11e9-8733-1c6cefdb6707.gif>
<sub>[View in Slack](https://battlesnake.slack.com/archives/C481H117Z/p1545260277108900)</sub>

**Comment by codeallthethingz** [comment]
> fancy :star-struck:
<sub>[View in Slack](https://battlesnake.slack.com/archives/C481H117Z/p1545261217117700)</sub>
