### ISSUE TITLE
autoplay=true parameter on board URLs

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#179]
Sometimes you want to have a game start automatically rather than wait for the play button to be pressed.

AC:
- adding `autoplay=true` to the querystring of a game URL will force it to autoplay instead of requiring you to click the play button

**Comment by brandonb927** [comment]
How would one enable this? We could make a settings page and provide an option there for this, maybe enabling other options?

**Comment by brandonb927** [comment]
This just needs to be deployed but can be considered done! If you're on a game screen, just add `?autoplay=true` to the URL and the game will start automatically once it receives the first frame.
