### ISSUE TITLE
Terms and Conditions while signing up / in

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#184]
Logging in to play should come with some kinda terms and conditions

**Comment by brandonb927** [comment]
@codeallthethingz can you outline the requirements and the intended flow, I could get this included this week.

**Comment by codeallthethingz** [comment]
Will to get text.

**Comment by codeallthethingz** [comment]
Lets add code of conduct too.

**Comment by codeallthethingz** [comment]
COC - https://github.com/battlesnakeio/community#code-of-conduct

**Comment by codeallthethingz** [comment]
Added a task to our internal asana to create the TOCs

**Comment by codeallthethingz** [comment]
Reassigned to Brandon as this is just waiting for a link from ops now.

**Comment by codeallthethingz** [comment]
Moving to asana.
