### ISSUE TITLE
Starter snakes root path should return documentation url

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#186]
Similar to the work that @SynthesizedSoul put into <https://github.com/battlesnakeio/starter-snake-python/pull/39/files#diff-4dd44bb1c9eb58791d7b4a226d9e4ee4R9>, I think it would be a great use of the root URL path in each starter snake to return a link to the Battlesnake Docs page.

AC
- some kinda reference to docs.battlesnake.io for all the standard starter snakes that is returned from the root path.

Implementation ideas
- link to the docs 
- iframe the docs

**Comment by codeallthethingz** [comment]
I don't think the snakes should have code that's not related to the snake in them.  
I do think it would be beneficial to have the READMEs point at the docs though?

**Comment by brandonb927** [comment]
Update: the consensus is that we want the root URL paths in all starter snakes to point to the docs somehow.

I think it should just return text saying "Get started by reading the docs: https://battlesnake.io/docs"

**Comment by brandonb927** [comment]
I have no idea how to do this in the [Java client](https://github.com/battlesnakeio/starter-snake-java/blob/master/src/main/java/io/battlesnake/starter/Snake.java), @codeallthethingz :)

**Comment by codeallthethingz** [comment]
@brandonb927 it's now in code review.

**Comment by brandonb927** [comment]
https://github.com/battlesnakeio/starter-snake-java/pull/5 was merged, this can now be closed! 🎉
