### ISSUE TITLE
Clearing form in new game form does not clear the snakes 

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#190]
Steps
- run a game with 8 snakes.
- create a new game with 2 snakes.

Actual
- game still runs with 8 snakes.

Expected
- 2 snakes.

**Comment by brandonb927** [comment]
I've seen this happen a few times and it has always bugged me. I'll fix this when I fix https://github.com/battlesnakeio/roadmap/issues/191

**Comment by brandonb927** [comment]
Fixed by https://github.com/battlesnakeio/play/pull/75
