### ISSUE TITLE
Sendwithus Bounty Snake

### ISSUE THREAD

**Issue by aforsilly** [battlesnakeio/roadmap#196]
We need to build one!

**Comment by joram** [comment]
are you sure you want to discuss our bountysnake publicly?! what about all our super snake secrets?

**Comment by CDFriend** [comment]
![mr_burns_evil](https://user-images.githubusercontent.com/8661121/51052557-ddf57800-158b-11e9-908d-b4ce205e58ab.gif)

**Comment by brandonb927** [comment]
Can we call it the  `D-hisssssss-patch` snake?

**Comment by joram** [comment]
I suggest we leave a back door where if you taunt in some call-and-response manner, our snake just circles in on itself.

**Comment by codeallthethingz** [comment]
@graeme-hill is this in progress?

**Comment by graeme-hill** [comment]
Nope

**Comment by brandonb927** [comment]
@graeme-hill did this! 🎉
