### ISSUE TITLE
battlesnake.io/docs should point to docs.battlesnake.io

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#197]
Currently, https://battlesnake.io/docs points to the old location of https://github.com/sendwithus/battlesnake, but seeing as we have a real docs site now if should point to http://docs.battlesnake.io.

**Comment by brandonb927** [comment]
@codeallthethingz who has access to this so they can change it? is it just a redirect on the squarespace site?

**Comment by codeallthethingz** [comment]
Done.

**Comment by brandonb927** [comment]
thanks @codeallthethingz
