### ISSUE TITLE
Rounded snake corners

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#198]
I just noticed in some of our slides from previous tutorial content, the snakes in the slides had curved bodies in the corners. I think we should do this again!

![image](https://user-images.githubusercontent.com/1509352/51135561-30829e80-17ef-11e9-8372-f143b737569f.png)

**Comment by codeallthethingz** [comment]
@nbw

**Comment by codeallthethingz** [comment]
Hey Nathan, how far did you get with this?

**Comment by brandonb927** [comment]
@nbw

**Comment by dlsteuer** [comment]
this is complete
