### ISSUE TITLE
Tournament Player

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#200]
AC
- A single URL for twitch to play each consecutive game for a named tournament.
- Brandon is happy and stress free during the competition presentation.
- The MCs don't have to turn to see the display

Implementation idea
- Tournament endpoint to get the id of the current game.
- Have an iframe that polls the tournament endpoint for a new game ID and if it changes reload the sub iframe.

**Comment by joram** [comment]
I have built the precursor to this, but it doesn't auto-refresh, there needs to be some loop of js to auto-refresh the iframe. It also should look pretty

**Comment by codeallthethingz** [comment]
Moved to play repo
