### ISSUE TITLE
Download Tournament structure

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#202]
If everything goes wrong we would like to be able to have an export from the current tournament.,
so that we can run a tournament without tournament mode.

**Comment by codeallthethingz** [comment]
@joram / @tristan-swu

**Comment by tristan-swu** [comment]
Johns says he's done
He didn't show me anything, and against my better judgement I'm going to believe him :)

**Comment by codeallthethingz** [comment]
Please link the PR before this is closed.

**Comment by joram** [comment]
https://github.com/battlesnakeio/play/commit/f598dbadb2312bf9745b240f22d5a5a6a7a825ba
it was already committed, just hasn't been deployed

**Comment by joram** [comment]
verified on prod
