### ISSUE TITLE
Avoid 4 snakes in the final round

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#207]
AC:
- can define max number of snakes per heat in a round.

**Comment by tristan-swu** [comment]
Do we want to configure this at the tournament level? So each heat has the same number of games for each round in the tournament?

**Comment by codeallthethingz** [comment]
yes.

**Comment by dlsteuer** [comment]
I don't think this should be configured at the tournament level this would require every bracket to have the same number of games per round but that won't work because there will be a much larger number of snakes in the beginners brackets vs the advanced.

**Comment by joram** [comment]
after much discussion, we'll do this by not allowing the second to last round to have 2 games (if possible), bumping to 3) so that we have 6 in the finals, not 4)

**Comment by codeallthethingz** [comment]
Moved to play repo
