### ISSUE TITLE
Ensure starter snakes are complete

### ISSUE THREAD

**Issue by LouisRitchie** [battlesnakeio/roadmap#21]
- [ ] Update starter-snake readme in the community page about having a tutorial video + readme for deploying to heroku.  Add the technology choice for the recordings and to contact Will to put the recordings in the Monty the Python youtube channel.
- [x] decide which language snakes we are going to officially support
- [ ] create tickets for doing the following for each of the supported snakes.

**Comment by ColDog** [comment]
This get's a big +1 from me as far as a ticket goes. Maybe we should break this up into every language that we'd like to see?

**Comment by codeallthethingz** [comment]
@joram I think this ticket should change to the following

Title: Ensure starter snakes are complete

- [ ] Update starter-snake readme in the community page about having a tutorial video + readme for deploying to heroku.  Add the technology choice for the recordings and to contact Will to put the recordings in the Monty the Python youtube channel.
- [ ] decide which language snakes we are going to officially support
- [ ] create tickets for doing the following for each of the supported snakes.

**Comment by brandonb927** [comment]
@joram any movement on this? Getting very close to the tourney...

**Comment by dlsteuer** [comment]
I think the starter snakes are pretty good as is, we made it through the 2019 battlesnake event, gonna close this.
