### ISSUE TITLE
Never use database IDs in routes

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#210]
Motivation: We shouldn't use auto-incrementing database IDs in routes or URLs. The reasons being that it exposes business information through URLs.

AC
- A PR should be opened that rids the app of using auto-incrementing IDs in URLs and routes.

**Comment by tristan-swu** [comment]
Why not?

**Comment by tristan-swu** [comment]
I'm not sure if I buy the security risk argument - if you can fuzz an api /w integers as keys, you can do it was identifiers like `snk_CJHqP4pYg3GT9KyG7RPFqaF3` as well. Can you give an example of how you want to change id behaviour in routes?

The engine uses a string primary key and generated id's like `snk_CJHqP4pYg3GT9KyG7RPFqaF3` using a uuid function. But at the end of the day - `snk_CJHqP4pYg3GT9KyG7RPFqaF3` is a primary key for a table. Perhaps its less predictable, but I'm not sure how a string id is more secure than an int id.
