### ISSUE TITLE
Leaderboard migrations fail on Postgres

### ISSUE THREAD

**Issue by tristan-swu** [battlesnakeio/roadmap#211]
When running the database migrations on Postgres, the leaderboard migrations fail with:
```
Applying leaderboard.0006_auto_20181221_2240...Traceback (most recent call last):
---snip---
django.db.utils.ProgrammingError: multiple primary keys for table "leaderboard_gameleaderboard" are not allowed
```

To reproduce:
 - Start up a *clean* database in postgres (no migrations, no data)
 - Modify your config to use it as a database (example below)
 - Run migrations on an empty database

Example config:
```
from settings.base import *

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": get_env("POSTGRES_DB", "battlesnakeio_play", True),
        "USER": get_env("POSTGRES_USER", None, False),
        "PASSWORD": get_env("POSTGRES_PASSWORD", None, False),
        "HOST": get_env("POSTGRES_HOST", None, False),
        "PORT": get_env("POSTGRES_PORT", None, False),
    }}
```

Running these migrations using the default (SQLlite) database do not fail. The root cause of this problem is differences between migrations on sqlite vs postgres.

I know sqlite is dead simple to use, but I would ***strongly*** recommend developing against the database that this will be deploying with. This saves us the pain of finding out these kinds of problems at the last minute.

**Comment by brandonb927** [comment]
I think squashing the current migrations would help alleviate and fix this. Are you running on a clean or older dataset in pg?

**Comment by tristan-swu** [comment]
I'm running on a totally clean dataset. 
Let me update the repro steps to include that.

**Comment by brandonb927** [comment]
Also pinging @joram here on this

**Comment by brandonb927** [comment]
@dlsteuer this commit is causing the issue https://github.com/battlesnakeio/play/pull/77/files#diff-94f3814a6f46b97171c600d67f069539

Any reason why Django added an `id` AutoField here?
