### ISSUE TITLE
Length mismatch between you.body and board.snakes[0].body

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#212]
You is one segment longer.

```
console.log('you ', request.you.body)
console.log('snake[0] ', request.board.snakes[0].body)

you  [ { x: 4, y: 4 }, { x: 4, y: 5 }, { x: 4, y: 6 } ]
snake[0]  [ { x: 4, y: 4 }, { x: 4, y: 5 } ]
```

**Comment by codeallthethingz** [comment]
> A quick question. Couldnt find anything in the docs regarding this issue. I run the engine in dev mode locally and when i log the size of the bodies it mismatches.
<sub>[View in Slack](https://battlesnake.slack.com/archives/C0E9EM0NM/p1547828139077100)</sub>

**Comment by dlsteuer** [comment]
No issue found here.
