### ISSUE TITLE
Add codeformatting (ie: black) to battlesnakeio/play

### ISSUE THREAD

**Issue by tristan-swu** [battlesnakeio/roadmap#218]
An easy win for code consistency is to use a code formatter on battlesnakeio/play.

We can debate if it runs as part of the CI check, but at the end of the day, having a 1 line command to auto-format the codebase would be helpful.

Black (https://github.com/ambv/black) can do this for us automatically.

**Comment by dlsteuer** [comment]
Added black/flake8 checks as a pre-commit hook in git.
