### ISSUE TITLE
Update the /ping endpoint in the docs to require a 200 OK response

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#219]
Currently the ping endpoint in the Docs states that the response is ignored, however this is counterintuitive to how we want to use the ping endpoint moving forward. @joram and I agree that Play should require a 200 OK response instead of ignoring the response.

**Comment by codeallthethingz** [comment]
I think this is one of those tickets where creating a PR is faster than creating a ticket?

**Comment by brandonb927** [comment]
I just wanted it tracked so someone can start the work, but yeah you're probably right here.
