### ISSUE TITLE
Error handling in engine API

### ISSUE THREAD

**Issue by graeme-hill** [battlesnakeio/roadmap#22]
Right now `server_test.go` only tests basic happy path. This change would add tests for unhappy path and then make those tests pass. In general that would mean implementing a bunch of the "TODO" comments in `server.go`.

Since this is meant to test `Server` and not the `ControllerClient` it would probably involve creating a mock controller that has an error object and then validating that `Server` handles that properly (in addition to a few other cases like invalid JSON).

I'm creating this as a starter issue to get my feet wet. If the change makes sense I will happily do it myself. If the API is still in flux and expected to change a lot then this might not be worth it yet.

**Comment by ColDog** [comment]
This looks great to me! The engine is definitely in somewhat of a state of flux that being said I think a test like this could easily be modified to fit with whatever structural changes happen. I'd say go for it!

**Comment by dlsteuer** [comment]
Yup this makes a lot of sense, and was on my todo list, so if you want to pick it up, that sounds awesome.
