### ISSUE TITLE
Set spawn locations for tournament board sizes

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#221]
Current sizes are

7x7, 11x11, 19x19

Starting position for 7x7 illustrated in the docs the other sizes of boards ensure starting 1 in from the edge on the same colour square in the same configuration.

http://docs.battlesnake.io/2019-tournament-game-rules.htm

**Comment by dlsteuer** [comment]
fixed by battlesnakeio/engine#76
