### ISSUE TITLE
game settings configurable at the bracket level

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#223]
tournament/models/tournaments.py:314 we create the tournament games. The variables shouldn't be hardcoded, they should be configured at the tournament bracket level

**Comment by brandonb927** [comment]
@joram this is one of those instances where a PR is probably better than opening an issue :)

**Comment by joram** [comment]
yeah, but it involves a migration, so I wanted a note for later.

**Comment by codeallthethingz** [comment]
Moved to play repo
