### ISSUE TITLE
tournament current game view should work with pre-running games

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#227]
Currently there is a `/tournament/<id>/current/game` url that shows the first game that is currently running.
We intend to prerun games for the tournament, which will break how that view works.

If we keep a flag on the `TournamentBracketGame` model, and only have one actively watched game in a tournament, it can be human controlled, and allow us to pace the viewing.

**Comment by codeallthethingz** [comment]
Moved to play repo issues for tournament.
