### ISSUE TITLE
Engine needs a persistent backend

### ISSUE THREAD

**Issue by ColDog** [battlesnakeio/roadmap#23]
Currently the engine is only backed by an in memory implementation. We need a persistent backend for when this is deployed to Google cloud or anywhere else.

We've had a bit of a discussion below about different alternatives. Redis is likely the easiest starting point to get started with. We would likely want to evaluate whether it's a good fit during implementation.

As reference the backend should implement the following interface:
https://github.com/battlesnakeio/engine/blob/master/controller/store.go#L32

Acceptance
- How long do we need to store it? (TTLs) - not gonna worry about it for the first release.. Persistent redis for the first data store. 30 days if we need to do it.
- how fast do the reads need to be (100 concurrent games running as a target. 1000 concurrent would be great, 1,000 people viewing).

Implementation idea
redis.

**Comment by daniel-swu** [comment]
I'm thinking we use google cloud datastore since the plan is to run in GKE, I think this makes a lot of sense.

**Comment by dlsteuer** [comment]
I'm thinking we use google cloud datastore since the plan is to run in GKE, I think this makes a lot of sense.

**Comment by ColDog** [comment]
Thinking that redis would be a good fit:

- Has a streaming architecture, stream in frames and stream them out via the API.
- Supports a good use case of locking a game.

**Comment by codeallthethingz** [comment]
@ColDog closing in favour of #70

**Comment by dlsteuer** [comment]
@codeallthethingz I think this ticket is fundamentally different then #70 this is about having a backend that persists around server reboots, when you probably have an ephemeral file store. I.e some sort of database backend, which we will need at some point once the server is up and running. While #70 is about persisting locally.

**Comment by graeme-hill** [comment]
For basic usage I think the file system version described in #70 *could* be used in production too, but it all depends on what functionality we want in the long term. It might make sense to start with just the file system implementation and then wait until it feels insufficient and implement redis or something.

**Comment by ColDog** [comment]
Ya we should definitely do both, while #70 is more useful in the short term. @codeallthethingz I'm going to reopen.

**Comment by codeallthethingz** [comment]
Needs acceptance
- How long do we need to store it?  (TTLs)
- how fast do the reads need to be
- how many reads do we need to support concurrently
- Are there price concerns?

**Comment by graeme-hill** [comment]
Also: is the `Store` interface finalized? If not then do we anticipate wanting read operations like "list all games in time frame" or "list all games including snake X". If we need to do any indexing other than just game ID then it makes a big difference.

**Comment by dlsteuer** [comment]
I think we can call the current interface complete, there was ways in Go to extend functionality without modifying interfaces, common go idiom is to keep interfaces as small as possible and when you need new functionality is add a new interface. Since interfaces in Go are implemented implicitly, we can add a type check for any new functional interfaces that are added.

**Comment by torbensky** [comment]
I noticed the inmem store returns an error for PopGameID. This isn't documented on the interface so afaik it's not necessarily required. I think a nil string would suffice and prefer that over using an error.

**Comment by dlsteuer** [comment]
It does return an empty string and an error. I'm not quite sure what you are referring too. The return type is string, error for PipGameID

**Comment by torbensky** [comment]
It does return both, but Go best practices dictate you check the error result first. So if you go by that convention, then that implementation returns the `ErrNotFound` error in that case.

**Comment by dlsteuer** [comment]
oh, I'm not entirely sure that Go best practices dictate that, if you look at the standard library, particularly database/sql, it will return sql.ErrNoRows when no result is found. I don't really like that and would prefer not. I think the store implementations should be consistent.

**Comment by dlsteuer** [comment]
I also think there is some confusion here about what you are talking about, so it might be best to discuss it in person.

**Comment by torben-swu** [comment]
I'm 100% onboard for consistency either way :+1:

**Comment by ColDog** [comment]
@torbensky / @dlsteuer Interface documentation is done via unit tests:

https://github.com/battlesnakeio/engine/blob/master/controller/store_test.go

These tests should pass for all stores.
