### ISSUE TITLE
Configurable Turn Delay

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#231]
Currently the turn delay in board is hard coded, we'd like to be able to specify this as a query string parameter.

**Comment by bvanvugt** [comment]
I'd really like to see this parameter expressed as 'fps' or 'max fps' -- I think that's most easily interpreted (and also self-restricting if we only allow ints)

**Comment by brandonb927** [comment]
This has been addressed! pass `frameRate=<fps>` where `fps` is a number
