### ISSUE TITLE
Board Javascript error

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#244]
It's possible for board to just stop playing in long running games, see attached image for stack trace.
<img width="1002" alt="screen shot 2019-02-15 at 11 07 40 pm" src="https://user-images.githubusercontent.com/326884/52896017-d3279780-3176-11e9-96f4-e30095b495a0.png">

**Comment by dlsteuer** [comment]
this was the game that caused the issue: https://play.battlesnake.io/g/40ce43c6-58f8-47fb-b472-5f7d45f7de94/?turn=2542 if you just play the game at board.battlesnake.io it seems to work fine.

**Comment by SynthesizedSoul** [comment]
@brandonb927 I think this issue has been raised by this refactor: https://github.com/battlesnakeio/board/commit/24a3c7099c1cbc8292bb0555e16912ea3a55eb54

It appears this may also be affecting the ability to link directly to moves.

Any thoughts on why? It appears, after diagnosing, it may be that the error being thrown is closing the web socket earlier than expected meaning we're not receiving all the frames.

**Comment by brandonb927** [comment]
Thanks for the extra context @SynthesizedSoul, I'll take a look at fixing this tonight.
