### ISSUE TITLE
Api is down 

### ISSUE THREAD

**Issue by ntmk** [battlesnakeio/roadmap#247]
![screenshot 5](https://user-images.githubusercontent.com/25558862/52921966-9ae89c00-32d1-11e9-94a3-fc6ce211cbf0.png)

**Comment by dlsteuer** [comment]
@ntmk thanks for the report, this is now fixed in https://github.com/battlesnakeio/docs/commit/236ad52ac52ab6409d42fb8bcbebf1aeea9436a4
