### ISSUE TITLE
Body SVG visible on tail after eating food

### ISSUE THREAD

**Issue by AdamK-PXU** [battlesnakeio/roadmap#248]
The SVG for the the tail should still be visible after eating food, even though it's stacked both the tail and the body on the same position.

![screen shot 2019-02-19 at 3 13 04 pm](https://user-images.githubusercontent.com/17360962/53054325-e5485500-3458-11e9-9522-5bbbcd604b62.png)

**Comment by codeallthethingz** [comment]
Exporter is also interested in the algorithmic fix for this as it's doing exactly the same thing.

**Comment by codeallthethingz** [comment]
@nbw

**Comment by brandonb927** [comment]
This has been fixed
