### ISSUE TITLE
Heroku deploy button in snake templates

### ISSUE THREAD

**Issue by nbw** [battlesnakeio/roadmap#25]
One-click deploy buttons from any snake templates that we publish. 

**Question:**  In line with our values, specifically "Teach real-world programming skills," do we want a one-click deploy or should give tutorials about how to interface with the heroku CLI, find the appropriate build pack, etc.. At the very least, if we give a one-click deploy I think we should explain what we're doing to accomplish that.

**Comment by codeallthethingz** [comment]
Brad: Teach real world skills is not necessarily "advanced" real world programming skills.
