### ISSUE TITLE
Let people know about the keyboard shortcuts

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#250]
As a snake developer, it's not immediately obvious that there are keyboard shortcuts to navigate the game.

Implementation idea
grey mini help text under the board?

![image](https://user-images.githubusercontent.com/1261268/53069576-4e4bbf00-3491-11e9-8f6c-90570f8b869f.png)

**Comment by brandonb927** [comment]
Would something like this work? 
![image](https://user-images.githubusercontent.com/1509352/53074650-2b74d700-34a0-11e9-9df2-2f8c383e95f3.png)

**Comment by xtagon** [comment]
Hi, some new insight:

When I reported this, it was because I didn't know how to play/move forward the board when testing on my local machine. It turns out it was because my browser window was too small, and the buttons were hidden. So I thought that keyboard shortcuts must be the only way to control it, but that was a mistaken assumption.

**Comment by xtagon** [comment]
Also, there is already keyboard shortcut text in the main website (as shown in the first screenshot) but there is nothing at all in the local engine server when you run it on your own machine.

**Comment by brandonb927** [comment]
@xtagon Totally understandable, this PR _also_ enables showing the keyboard shortcuts at smaller displays, so it crushes 2 issues with one PR 😄

**Comment by dlsteuer** [comment]
my preferred style would be a pop over or something on a question mark hint circle, I feel like always having them is too much.

**Comment by brandonb927** [comment]
@dlsteuer agreed, I can find another way to display them without being obtrusive

**Comment by brandonb927** [comment]
Does something like this make sense?

![](https://user-images.githubusercontent.com/1509352/53258673-19eb2500-3682-11e9-8d7f-c2cb82192b92.gif)
