### ISSUE TITLE
Snakes can't be deleted

### ISSUE THREAD

**Issue by exzizt** [battlesnakeio/roadmap#252]
I've tried to delete an old snake a few times and it keeps coming back.

**Comment by brandonb927** [comment]
@exzizt You can delete a snake by going to your snake's public page, clicking the dropdown on the right, then delete.

![image](https://user-images.githubusercontent.com/1509352/53213336-5de81680-35fd-11e9-9a22-6e449ec68366.png)

**Comment by brandonb927** [comment]
@exzizt This does look like a bug, we'll get a fix out.

**Comment by brandonb927** [comment]
We can confirm this has been fixed now
