### ISSUE TITLE
Editing a snake's URL is not saved

### ISSUE THREAD

**Issue by exzizt** [battlesnakeio/roadmap#253]

**Comment by brandonb927** [comment]
Hey @exzizt I can't seem to reproduce this issue, can you jump on to the Battlesnake Slack and we can chat further about it?

**Comment by exzizt** [comment]
@brandonb927 This is really weird, it seems to have saved the URL now. I refreshed the page to double check a few secs after and it wasn't changed--but now, it is.

**Comment by brandonb927** [comment]
@exzizt This does look like a bug after testing a bit, we'll get a fix out.

**Comment by brandonb927** [comment]
We can confirm this has been fixed now
