### ISSUE TITLE
Rough concept of what gradients/textures could look like for snakes

### ISSUE THREAD

**Issue by exzizt** [battlesnakeio/roadmap#255]
Didn't spend much time on this but primary/secondary colours could be re-introduced in the form of gradients, and also what it could look like if snakes could send an image to use as a texture. Made very quickly in Photoshop. Just throwing it out there.
![roughconceptbscolourgradientstextures](https://user-images.githubusercontent.com/17113094/53276437-d3162300-36b3-11e9-9afb-623322278056.png)

**Comment by dlsteuer** [comment]
Thanks for the idea, at this point in time, this isn't a direction we want to move in. There is also some significant architecture issues that would hinder accomplishing this.
