### ISSUE TITLE
Elixir snake needs updating

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#261]
The Elixir snake needs to be updated to remove taunts, and probably needs a once over to make sure it’s ip to spec with 2019 API https://github.com/battlesnakeio/starter-snake-elixir/blob/master/lib/elixir_snake.ex

**Comment by MarkZsombor** [comment]
I can deal with that. I've been actively using it, it works with the 2019 API but the taunts were included when their use in the tournament was still a question mark.

**Comment by brandonb927** [comment]
Thanks @MarkZsombor! If you want to close this by linking in the PR description when you have a PR up, that'd be great.
