### ISSUE TITLE
Getting up to speed with "Engine"

### ISSUE THREAD

**Issue by nbw** [battlesnakeio/roadmap#27]
Updating the Engine README.md with setup instructions.

# Note

I've been talking to Daniel already to document some setup instructions.

For those trying it out in the meantime:

* Install Go
* Set your GOPATH and add $GOPATH/bin to your PATHs
* `go get` to download deps, `go build` to create an executable or use `Make run`
* to create and run a game, first start the app (instruction above) and separately run `make run-game`  -- you'll need [JQ](https://stedolan.github.io/jq/download/) installed
* etc..

Note: the API has already changed, I'll probably document that as well -- somewhere.

**Comment by dlsteuer** [comment]
This is a great start, feel free to open a pr on the engine repo with this in the readme

**Comment by codeallthethingz** [comment]
@nbw Just in case you didn't see this ^

**Comment by codeallthethingz** [comment]
Closing as engine now has a readme.
