### ISSUE TITLE
Send /start request to snakes

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#31]
Currently the engine doesn't send the /start request to any of the snakes, this needs to be fixed and updated.

**Comment by graeme-hill** [comment]
I have the start and end requests being sent out now. As part of this issue should I also implement any engine code to gather the responses from /start (which is just color right now) and store them on the game state somewhere? Or will that be a different issue?

**Comment by dlsteuer** [comment]
Yeah, I think that is part of this ticket, it might require some controller updates though to be able to update the snake information.
