### ISSUE TITLE
Architecture Diagram

### ISSUE THREAD

**Issue by will-swu** [battlesnakeio/roadmap#34]
So we can see all the tech involved and the way data flows around the systems.
Probably this should go in the community repo?

**Comment by codeallthethingz** [comment]
@ColDog did you do this?  I'll close out if you post a link

**Comment by codeallthethingz** [comment]
Lets do this in the next meetup on a whiteboard and take a picture of it and then we're done.

**Comment by will-swu** [comment]
![img_20180530_173740](https://user-images.githubusercontent.com/35037777/41008661-104d7d28-68e1-11e8-885e-32ac8b64c8c9.jpg)

**Comment by codeallthethingz** [comment]
https://github.com/battlesnakeio/community/pull/23
