### ISSUE TITLE
Engine API Web-Sockets

### ISSUE THREAD

**Issue by ColDog** [battlesnakeio/roadmap#36]
Websockets will be needed to push game ticks up to the Javascript frontend.

This feature includes:
- Writing up a spec for websockets in the `api` package inside the engine project.
- Prototyping a websocket implementation.

**Comment by bvanvugt** [comment]
Will this be publicly available? Or private to the official board?
ie: what level of documentation is required?

**Comment by dlsteuer** [comment]
It will be publicly documented as part of the engine api spec
