### ISSUE TITLE
Make Python starter snake 2019 compatible

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#37]
Old snake here: `archived-starter-snake-python`

Acceptance
- compatible with the new snake API
- deployable on heroku
- project renamed to get rid of `archived-`
- Add license: MIT

**Comment by CDFriend** [comment]
Should we wait for the API to be finalized, or is the one here close enough?
https://github.com/battlesnakeio/docs/blob/master/apis/snake/spec.yaml

**Comment by dlsteuer** [comment]
Yeah that spec is what it's most likely going to be, that is the spec the current engine is built to, so if the starter snake is updated to the linked spec, it will work with the engine.

**Comment by CDFriend** [comment]
Sounds good - I should be able to get this done in the next couple days.

**Comment by codeallthethingz** [comment]
@CDFriend added you as a collaborator with read access.  Once you accept the invite you should be able to assign to yourself.

**Comment by CDFriend** [comment]
@codeallthethingz Accepted the collaborator invite, but still don't seem to be able to change the issue assignees. 

From github docs: https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/
> If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

Maybe I have to be an org member?

**Comment by CDFriend** [comment]
Would it be worthwhile to update this snake for python 3 as well?

**Comment by CDFriend** [comment]
@codeallthethingz Added a PR for the 2019 spec changes. The only remaining change would be renaming the repo.

https://github.com/battlesnakeio/archived-starter-snake-python/pull/31
