### ISSUE TITLE
Make Java starter snake 2019 compatible

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#39]
Old snake here: `archived-starter-snake-java`

Acceptance
- compatible with the new snake API
- deployable on heroku
- project renamed to get rid of `archived-`
- Add license: MIT

**Comment by ajdeziel** [comment]
I'll take care of this!

**Comment by ajdeziel** [comment]
Shouldn't the license be AGPL, not MIT?

**Comment by dlsteuer** [comment]
All the starter snake repos are going to be MIT licensed. We tracked that somewhere, but I don't know where it's documented anymore. The non-starter repos like engine/play/board etc. are AGPL

**Comment by ajdeziel** [comment]
Ok thanks!

**Comment by codeallthethingz** [comment]
first pass: https://github.com/battlesnakeio/archived-starter-snake-java/pull/1
