### ISSUE TITLE
Make Ruby starter snake 2019 compatible

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#41]
Old snake here: `archived-starter-snake-ruby`

Acceptance
- compatible with the new snake API
- deployable on heroku
- project renamed to get rid of `archived-`
- Add license: MIT

**Comment by codeallthethingz** [comment]
@wilson496  did you start work on this?

**Comment by wilson496** [comment]
Haven't had a lot of time to work on this. I made a basic template for it. 

I'll make a pull request to compare.

**Comment by nbw** [comment]
taking this one.
