### ISSUE TITLE
Simplify Engine Controller Interface

### ISSUE THREAD

**Issue by ColDog** [battlesnakeio/roadmap#43]
Workers inside the engine currently follow this pattern to retrieve a game, lock it and begin performing work on it:

1. Create is called (from the api).
2. Start is called (from the api).
3. Pop is called by the worker, since the game is started and unlocked, the active game id is returned to the worker in this call.
4. Lock is called by the current worker.
5. The worker initiates work and begins pushing game ticks through AddGameTick. The worker will also call Lock continually to keep the lock token valid.
6. Once work is finished, the worker will call EndGame and Unlock the game.

Simplifications that could be made:
1. When `Pop` is called, also `Lock` the game.
2. Create a `Heartbeat` call that checks game status as well OR if the worker is not sleeping for a variable time between ticks, then move the heartbeat logic into the `AddGameTick` call.
3. When `EndGame` is called unlock the game.

If (1) and (3) are done, we could remove the `Lock` and `Unlock` calls from the Controller which would help simplify understanding I think. If (2) is done we can remove a goroutine from the worker and reduce complexity there.

**Comment by ColDog** [comment]
@dlsteuer what do you think?

**Comment by dlsteuer** [comment]
Yeah this sounds great to me, and I'm in favour of removing the turn delay from the worker.

#33
