### ISSUE TITLE
API Engine Spec

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#47]
There was some discussion in battlesnakeio/engine#15  about the urls for the engine. This task is the placeholder for building a spec for the engine

**Comment by bvanvugt** [comment]
Spec should be written as an OpenAPI 3.0.1 spec and kept along side the Snake API spec, here:
https://github.com/battlesnakeio/docs/tree/master/apis

Also note that we're using dated versioning.

**Comment by codeallthethingz** [comment]
@dlsteuer   I think this is now done: https://github.com/battlesnakeio/docs/blob/master/apis/engine/spec 

?

**Comment by dlsteuer** [comment]
I just added an update to the spec, which gives the extra parameters on the frames call, and adds the websocket url
