### ISSUE TITLE
How to handle a stop game

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#50]
Currently a worker picks up a game and runs it to completion and there isn't a way for the controller to signal the worker to pause the currently running game.

**Comment by codeallthethingz** [comment]
Colin: Probably when it writes the GameTick just return that the game is stopped.

**Comment by codeallthethingz** [comment]
Daniel: What do you think about cancelling the context, that the worker is using? This would place the logic in the worker instead of in the game tick lop

**Comment by ColDog** [comment]
Oh, this is handled, or maybe not? Hmm, don't actually have a test case for it. I don't know if per frame / per game workers makes a significant difference here this is relatively easy to handle either way.

@bvanvugt if you're curious, the per-game workers implementation is pretty much complete. The best description is the proto file: https://github.com/battlesnakeio/engine/blob/master/controller/pb/controller.proto.

The interesting thing is it's super easy to change the implementation to one or the other so we can start to kind of compare the implementations now that we have a bit of a foundation to work on.

**Comment by bvanvugt** [comment]
Got it, neat. My thought was that per-frame gives us an easy window to "pause" or "halt" running games.

**Comment by codeallthethingz** [comment]
Closing as I think this is taken care of.  Please reopen if I'm wrong
