### ISSUE TITLE
Actually archive the 'archived-starter-* repos?

### ISSUE THREAD

**Issue by bvanvugt** [battlesnakeio/roadmap#53]
@codeallthethingz can we also officially archive the old starter snake repos? they'll still be public visible, like the older game server repos.

**Comment by will-swu** [comment]
I was thinking these would actually be turned into the new starter snakes and renamed.   I think they're going to be mostly the same.

**Comment by graeme-hill** [comment]
Ya that's what I expected as well. We could just rename and update. Maybe also tag the last commit before changes with `2018-final` or something.
