### ISSUE TITLE
Write first draft of community Code of Conduct

### ISSUE THREAD

**Issue by bvanvugt** [battlesnakeio/roadmap#6]
We need a code-of-conduct.md file in the community repo.

**Comment by bvanvugt** [comment]
I like what @codeallthethingz has already done by referencing the CNCF Code of Conduct - we can probably just reference it directly and maybe add a few choice pull quotes.

See https://github.com/kubernetes/community/blob/master/code-of-conduct.md

**Comment by codeallthethingz** [comment]
agreed.
