### ISSUE TITLE
start game with dropdown for "my snakes"

### ISSUE THREAD

**Issue by joram** [battlesnakeio/roadmap#62]
As a battlesnaker 
I can start a game without having to remember my URLs
such that I can quickly get a game up and running.

Acceptance
- UI to start a game.  
- Snake input fields are autocomplete referencing snakes that you have run in the past? 
- You can add up to X snakes
- Validate snakes are alive when you add them to the input field, illustrate liveness next to the input field.
- Button to start the game

**Comment by codeallthethingz** [comment]
moved to 1.1 as we don't need this for launch.

**Comment by brandonb927** [comment]
I added this to the Polish milestone

**Comment by codeallthethingz** [comment]
This is done.  I believe you did it Brandon. :)
