### ISSUE TITLE
Dockerize play

### ISSUE THREAD

**Issue by brandonb927** [battlesnakeio/roadmap#68]
It would be great to not have to install everything in the project in a virtualenv, and manage python versions etc. plus we're going to be deploying this eventually and will need a containerized version of it to do so? I would like to do this because I don't run Linux either.

**Comment by bvanvugt** [comment]
This is tough - we made the call early on to not use docker for dev. It'd be easy and consistent to expect every repo to product a runnable docker image for that component, but that's not the same as using docker for dev...

I think this is worth discussing at the next meeting.

**Comment by codeallthethingz** [comment]
We will be deploying this as a build artifact, but we don't want to manage a development environment in docker internally.

**Comment by codeallthethingz** [comment]
Closing as we don't want to support this.
