### ISSUE TITLE
Add standard CONTRIBUTING.md file to every repo that points to community contributing guide

### ISSUE THREAD

**Issue by bvanvugt** [battlesnakeio/roadmap#7]
Write a simple, standard CONTRIBUTING.md file that points to a master contributing guide in the Community repo.

This standard file needs to be added to the following repos:
- docs
- roadmap
- engine
- play
- board
- branding
- website

**Comment by bvanvugt** [comment]
@codeallthethingz is this complete now?

**Comment by codeallthethingz** [comment]
Yep.
