### ISSUE TITLE
Save games to file system

### ISSUE THREAD

**Issue by graeme-hill** [battlesnakeio/roadmap#70]
The current engine just uses an in-memory store for games. I have heard that there might be a real database version later (like maybe google cloud store?). I think it would make sense if the default dev mode storage option saves data to hard drive as a single file per game. It should accomplish the following:

1. Sharing a game is just copying/sending a file.
2. In-progress games can be resumed if the server restarts part way through.
3. File is easy to parse in multiple languages to facilitate GUIs, testing tools, machine learning, etc.

For my own benefit I already made a modified version of `inmem` that saves the game to a json file after it's complete, but this does not help with item `2` described above and json isn't really a very good format for that. It's better to have some format that can be continuously appended to (like csv).

**Comment by dlsteuer** [comment]
This is something I've had in mind. One thing you could do for serialization is use the protobuf format, it's not human readable like json is, but the files would be smaller, and all objects right now are protobuf objects, so you can use the proto package serialization.

**Comment by graeme-hill** [comment]
Just did some reading on the protobuf format and it looks like you can simply append more repeated data like with csv so I will try that out when I get a chance. The format isn't quite as simple as JSON but since we can provide the proto schema it's still pretty darn simple.

Right now the JSON format looks something like this:

```
{
  "board": { ... },
  "snakes": [ ... ],
  "turns": [
    ...
    ...
    ...
    ...
  ]
}
```

`turns` doesn't store the whole state of the game at each turn. Instead it just stores the move of each player, and `snakes` stores the starting state. I might have to add some stuff to the proto schema to do it that way instead of just storing a collection of `pb.GameTick`.

I can look into this later when I get some time.

**Comment by colin-swu** [comment]
Oh this is a cool idea, hadn't thought of this at all! I made this issue a while back: https://github.com/battlesnakeio/roadmap/issues/23. You *could* share a redis dump file, but that would suck way more than just a CSV.

Either way this looks great, I personally would find this very valuable. Maybe take a peek at this project? https://github.com/nanobox-io/golang-scribble

**Comment by graeme-hill** [comment]
After trying a few things I have found that it works best with a file format like this:

```
{"id":"e9e0710e-6f82-4e39-8740-402345f000b9","width":10,"height":10, ... }
{"turn":0,"snakes":[ ... ]}
{"turn":1,"snakes":[ ... ]}
...
```

It's just one json object per line (without top level square brackets) where the first line is data that applies to every frame like id, board size, snake URLs, etc. This means that parsing pseudo-code is:

```
gameInfo := parseJSON(lines[0])
frames := []
for each line in frames[1:]:
    frames.add(parseJson(line))
```

The CSV thing didn't work out because you can't really just store the sequence of moves, you actually do need a snapshot at each frame because you cannot derive food positions after one is eaten, and it's possible that games rules could change and then replaying the game would have a different result.

It also didn't make sense to make it a completely valid JSON file because then I would have to put the file into a temporarily invalid state when I write to it. This would mean implementing transactionality with a journal or with multiple files that get swapped. Using this technique if the process dies part way through writing a turn then it's easy for a reader to read all previous frames and then consider the corrupt frame at the end to be an incomplete turn and resume the game from the frame before.

Also I looked into scribble and it didn't quite seem to fit. I think it is a document database with one file per document and you can upsert, delete, etc. But if you want to append data onto an existing document you need to continuously upsert the whole document. With this technique I can stream onto the end of the file as the game is run so that if it dies at any point no data is lost.

**Comment by graeme-hill** [comment]
So after experimentally implementing this is a way that ticks all the boxes, I feel like it's not worth it because it turned out to be more complex than I expected and IMO it's not worth maintaining and extra non-trivial store implementation. I think it would make more sense to keep the existing in-memory store, then eventually add in the redis (or similar) store. Instead we could have a feature in play to download a game as json. Then instead of copying the file from your HD you can click a button to download the json file. This works with any store and you don't need access to the server's file system to get it.

**Comment by ColDog** [comment]
Nice, this makes sense. I like the download as JSON button idea. Maybe there's a bigger ticket here on how we'd want to export games? I was thinkinng the server would just continually export games maybe as soon as it's finished with them.

**Comment by graeme-hill** [comment]
Just created #78

**Comment by dlsteuer** [comment]
This is interesting, I would still find it useful to not lose games, when stopping and starting the engine, and not require some other data store like redis. I'm thinking for example a developer who is using windows and can't just docker run redis. Being able to have the inmem store flush and restore from disk would be quite useful. I'd like to keep this one open

**Comment by graeme-hill** [comment]
oh ok well I have a branch and I can make a PR if you want

**Comment by dlsteuer** [comment]
Sure you can make a pr, did you do a new store implementation or extend the existing inmem store? Also if you want to make it simpler, it could just flush the map to disk using something like https://golang.org/pkg/encoding/gob/, the files on disk don't have to be readable, especially if something like #78 is available.

**Comment by graeme-hill** [comment]
Ya that's what I'm thinking now too. With the export feature we can just write the proto binary objects or use a lib like you suggested. I'll look into that.
