### ISSUE TITLE
Failure to respond to /start is considered a death

### ISSUE THREAD

**Issue by dlsteuer** [battlesnakeio/roadmap#71]
In PR battlesnakeio/engine#23 it was at first proposed that a snake that fails to respond to /start is considered a death and removed from the game, with a death cause like FailedToStart.

**Comment by graeme-hill** [comment]
Just to be clear, I decided *not* to kill snakes that don't respond to /start in that PR after discussion. But it still needs to be decided what the correct behaviour is. Currently snakes that do not implement /start, or that implement it incorrectly will just get assigned a random colour and they still get sent /move calls.

**Comment by codeallthethingz** [comment]
It's a no snake just continues in the direction.
