### ISSUE TITLE
Engine command line args are a bit wonky

### ISSUE THREAD

**Issue by graeme-hill** [battlesnakeio/roadmap#74]
For example there is a flag for api endpoint is defined like this:

```go
flag.StringVar(&apiAddr, "api listen", ":3005", "api listen address")
```

The second param is the command line flag, so it means that I have to use it like this:

```
engine --"api listen" :3007
```

Probably we want something more like this:

```
flag.StringVar(&apiAddr, "api-addr", ":3005", "api listen address")
```

so it can be used like this:

```engine --api-addr :3007```

The same goes for the controller endpoint flag.

**Comment by daniel-swu** [comment]
Yup this should be fixed, thanks for adding the issue.

**Comment by dlsteuer** [comment]
Yup this should be fixed, thanks for adding this issue.
