### ISSUE TITLE
Board MVP

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#75]
As a beginner battlesnake developer 
I can easily launch a UI that will allow me to run my snake battles.

Acceptance
- [x] Runs in latest versions of:
	- [x] Chrome
	- [x] Firefox
	- [x] Safari
- [x] Can easily differentiate between snakes.
- [x] Can tell where the head / tail is at all times.
- [x] Dead snakes remain, but don't obscure the rest of the battle.
- [x] Can easily visualize the health of the snakes
- [x] Type of death is visualized (wall, head collision, snake collision, starvation, etc...) 
- [x] Game ID / Engine location should be URL parameters so the board can be stateless.
- [x] Snake visualization should be SVG based
- [x] package script, that builds all assets so they could be deployed to S3 or something like that

Technology Acceptance
- [x] Technology chosen supports custom heads / tails without introducing a technological barrier to entry
- [x] Technology chosen supports recording of gifs for sharing on social media.
- [x] Large and vibrant communities behind technologies chosen.
- [x] Serverless - should all run in a browser and hit CORS endpoints on engine.

Emotional Acceptance
- [x] As this component is critical for the success of the Battlesnake 2019 event, be emotionally prepared for the small chance that the game master might come along and throw all your code out in favour of managing this internally.

**Comment by LouisRitchie** [comment]
@graeme-hill https://github.com/louisritchie/battlesnake-2019-board

**Comment by LouisRitchie** [comment]
Here is a Gist that is the modified `server.go` file for the Go engine. The modifications are attaching CORS-permitting headers to every request. (I'm not a Go developer, so it's very naive!)

https://gist.github.com/LouisRitchie/0f21b2347c38ad7fc5d1fc74bd76be67

**Comment by dlsteuer** [comment]
Another requirement needs to be a package script, that builds all assets so they could be deployed to S3 or something like that

**Comment by codeallthethingz** [comment]
@brandonb927  is gonna take a crack at type of death.

**Comment by codeallthethingz** [comment]
I think we're done for play? :)
