### ISSUE TITLE
Support CORS

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#76]
board will need CORS access to the engine.

Notes - Gin has nice support https://github.com/gin-contrib/cors

**Comment by daniel-swu** [comment]
It looks like the Gin middleware requires you to use the gin router functionality, so that would be a full buy in situation.

**Comment by dlsteuer** [comment]
It looks like the Gin middleware requires you to use the gin router functionality, so that would be a full buy in situation. Could use something like https://github.com/rs/cors for default net/http

**Comment by dlsteuer** [comment]
started working on this, we're actually using httprouter forgot about that. The linked project will work with that though.
