### ISSUE TITLE
Zeros omitted from json in API responses

### ISSUE THREAD

**Issue by graeme-hill** [battlesnakeio/roadmap#87]
In these API endpoints:

* `/games/:id/frames`
* `/socket/:id`

The data sent to the client are JSONized `pb.GameFrame` objects. Since the proto code generator adds the `omitempty` option to every field, integers are not included in the json when their value is zero. This isn't an issue when the client is also in Go because it just defaults to zero anyways. However, for a JS client it's pretty weird and unexpected. For example in my board PR (battlesnakeio/board#2) I had to add this:

```javascript
// This is a workaround for fields that are omitted when they have the default
// value. ie: int fields that need to default to 0 rather than undefined.
function cleanFrame(frame) {
  frame.Turn = frame.Turn || 0;

  for (const snake of frame.Snakes) {
    for (const part of snake.Body) {
      part.X = part.X || 0;
      part.Y = part.Y || 0;
    }
  }

  for (const food of frame.Food) {
    food.X = food.X || 0;
    food.Y = food.Y || 0;
  }
}
```

Not sure if this is a bug.

**Comment by dlsteuer** [comment]
Yes I think this is a bug, it's also a side effect of exposing the protobuf based objects outside the controller. It also looks like we probably shouldn't be using the standard encoding/json package for serialization, see https://godoc.org/github.com/golang/protobuf/jsonpb which is the protobuf -> json serialization package. But it looks like though that package will still omit the empty fields. In which case, the api might need to provide it's own structs so we can manage the tags, or use something like jsontag from the gogoproto project https://github.com/gogo/protobuf/blob/master/extensions.md#more-serialization-formats

**Comment by nbw** [comment]
working on a PR for this.

**Comment by codeallthethingz** [comment]
Completed with #44
