### ISSUE TITLE
Change the function new<SnakeRequest> --> DecodeSnakeRequest

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#95]
allocate struct outside of the function.

This is for clear understanding of allocation

**Comment by codeallthethingz** [comment]
@zrdaley  we had a quick discussion internally and we think you were right all along.
Referenced in the video.

**Comment by zrdaley** [comment]
Nice! I can make another PR to the go snake.

**Comment by codeallthethingz** [comment]
Done!
