### ISSUE TITLE
Create a helm chart for all the things.

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#98]
- [x] play
- [x] engine
- [x] redis
- [x] postgres

**Comment by codeallthethingz** [comment]
There is a test helm chart inside the infrastructue that can be used as a starting point.
@matthieudolci  can you add a link?

**Comment by matthieudolci** [comment]
here is the link to the template helm chart for services needing an ingress [Test chart](https://github.com/battlesnakeio/infrastructure/tree/master/charts/test)
