### ISSUE TITLE
Games aren't flipping to completed they become stopped

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#99]
1. Start engine
2. Create and run game
3. Wait for game to complete
4. Check game status is stopped instead of complete

Acceptance
- e2e test that games end in completed state.

**Comment by codeallthethingz** [comment]
@dlsteuer can you add steps to reproduce.

**Comment by dlsteuer** [comment]
So this appears to have resolved it self, after some of the changes since I last checked 🤷‍♂️ going to close now.
